name: Minecraft Server

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  mc:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Restore Repo
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Start Auto Backup Loop
        run: |
          (
            while true
            do
              sleep 300
              git config user.name "github-actions"
              git config user.email "actions@github.com"
              git add -A
              git commit -m "Auto backup" || true
              git push || true
            done
          ) &

      - name: Start Minecraft Server
        run: |
          java -Xmx16G -Xms4G -jar server.jar --nogui

      - name: Final Backup
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Final backup" || true
          git push || true
